name: flutter_inappwebview_example
description: Demonstrates how to use the flutter_inappwebview plugin.

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.4
  path_provider: 2.0.9
  permission_handler: 10.0.2
  url_launcher: 6.1.6
  flutter_inappwebview:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

  pedantic: ^1.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/index.html
    - assets/page-1.html
    - assets/page-2.html
    - assets/js/
    - assets/css/
    - assets/images/
    - assets/favicon.ico
    - assets/sample_audio.ogg
    - assets/sample_video.mp4
    - test_assets/certificate.pfx
    - test_assets/in_app_webview_initial_file_test.html
    - test_assets/in_app_webview_on_load_resource_test.html
    - test_assets/in_app_webview_javascript_handler_test.html
    - test_assets/in_app_webview_on_load_resource_custom_scheme_test.html
    - test_assets/in_app_webview_on_console_message_test.html
    - test_assets/in_app_webview_on_create_window_test.html
    - test_assets/in_app_webview_on_js_dialog_test.html
    - test_assets/js/
    - test_assets/css/
    - test_assets/images/
    - test_assets/favicon.ico
    - test_assets/sample_audio.ogg
    - test_assets/sample_video.mp4